### ISSUE TITLE
Basketball script runtime problem

### ISSUE THREAD

**Issue by Rebecca-123** [pollen-robotics/reachy2021-unity-package#12]
- Reachy's gripper knocks the ball off the table before it first attempts it's shooting motion

**Comment by FabienDanieau** [comment]
Indeed I reproduced this problem with Windows 11 and Unity 2021.3.6.
You can fix this by forcing the arm to go up before going above the ball. Could you test the following code?
https://gist.github.com/FabienDanieau/18c0829de579133a6246213f6b242686
Thanks

**Comment by Rebecca-123** [comment]
Awesome! the new script works, thanks!

**Comment by FabienDanieau** [comment]
Great. This script has been added to the Medium article.
