### ISSUE TITLE
I wonder where I can get the VR teleoperation app.

### ISSUE THREAD

**Issue by ZorAttC** [pollen-robotics/reachy2021-unity-package#25]
I read through the whole doc page of the Reacny robot and I can't find the VR teleoperation app,is it open-source?,or you guys missed to push it.

**Comment by FabienDanieau** [comment]
Hi @ZorAttC, the app is not released yet. But it will be soon. I'll keep you posted

**Comment by ZorAttC** [comment]
> Hi @ZorAttC, the app is not released yet. But it will be soon. I'll keep you posted

Thank you

**Comment by FabienDanieau** [comment]
We just released the app here: https://github.com/pollen-robotics/ReachyTeleoperation
